=== Mariortega83/LMSGI.1/XML/Curriculum/curriculum.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="curriculum" type="T_Curriculum" />

  <xs:complexType name="T_Curriculum">
    <xs:sequence>
      <xs:element name="datos_personales" type="T_Datos_Personales" />
      <xs:element name="datos_contacto" type="T_Datos_Contacto" />
      <xs:element name="datos_opcionales" type="T_Datos_Opcionales" minOccurs="0"/>
      <xs:element name="formacion_academica" type="T_Formacion_Academica" maxOccurs="unbounded" />
      <xs:element name="idiomas" type="T_Idiomas" maxOccurs="unbounded" />
      <xs:element name="experiencia_laboral" type="T_Experiencia_Laboral" maxOccurs="unbounded" />
      <xs:element name="competencias_socio-profesionales" type="T_competencias" />
      <xs:element name="datos_adiccionales" type="T_datos-add" />
    </xs:sequence>

  </xs:complexType>


  <xs:complexType name="T_Datos_Personales">
    <xs:sequence>
      <xs:element name="nombre" type="xs:string" />
      <xs:element name="apellidos" type="xs:string" />
      <xs:element name="fecha_nacimiento" type="xs:date" />
      <xs:element name="lugar_nacimiento" type="xs:string" />
      <xs:element name="nacionalidad" type="xs:string" maxOccurs="unbounded" />
      <xs:element name="n_identificacion" type="T_identificacion" />
      <xs:element name="archivo_foto" type="xs:string" />
    </xs:sequence>
  </xs:complexType>


<!-- Restricción de los caracteres del DNI -->
  <xs:simpleType name="Dni">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{8}[A-Z]" />
    </xs:restriction>
  </xs:simpleType>


  <xs:complexType name="T_identificacion">
    <xs:simpleContent>
      <xs:extension base="Dni">
        <xs:attribute name="tipo" type="xs:string" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>


  <xs:complexType name="T_Datos_Contacto">
    <xs:sequence>
      <xs:element name="tipo_via" type="xs:string" />
      <xs:element name="nombre_via" type="xs:string" />
      <xs:element name="numero" type="xs:integer" minOccurs="0" />
      <xs:element name="escalera" type="xs:string" minOccurs="0" />
      <xs:element name="piso" type="xs:string" minOccurs="0" />
      <xs:element name="puerta" type="xs:string" minOccurs="0" />
      <xs:element name="codigo_postal" type="T_CP" />
      <xs:element name="pais" type="xs:string" />
      <xs:element name="email" type="T_Email" />
      <xs:element name="telefono_movil" type="T_Telefono" />
      <xs:element name="telefono_fijo" type="T_Telefono" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

<!-- Restricción de los caracteres del Código Postal-->
  <xs:simpleType name="T_CP">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{5}" />
    </xs:restriction>
  </xs:simpleType>

<!-- Restricción de los caracteres del Email-->
  <xs:simpleType name="T_Email">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}" />
    </xs:restriction>
  </xs:simpleType>

<!-- Restricción de los caracteres del Teléfono-->

  <xs:simpleType name="T_Telefono">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{9}" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="T_Datos_Opcionales">
    <xs:sequence>
      <xs:element name="pagina_web" type="xs:string" minOccurs="0" />
      <xs:element name="cuenta_red_social" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="T_Formacion_Academica">
    <xs:sequence>
      <xs:element name="nombre" type="xs:string" />
      <xs:element name="centro" type="xs:string" />
      <xs:element name="fecha_inicio" type="xs:date" />
      <xs:element name="fecha_fin" type="xs:date" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="T_Idiomas" >
  <xs:sequence>

      <xs:element name="idioma" type="xs:string" />
      <xs:element name="nivel_comprension_oral" type="valor_idioma"/>
      <xs:element name="nivel_expresion_oral" type="valor_idioma"/>
      <xs:element name="nivel_comprension_escrita" type="valor_idioma"/>
      <xs:element name="nivel_expresion_escrita" type="valor_idioma"/>
      <xs:element name="nivel_titulo" type="nivel_idioma"/>
      
    </xs:sequence>
  </xs:complexType>


 <!-- Restricción de los niveles en cada aspecto del idioma -->
  <xs:simpleType name="valor_idioma">
    <xs:restriction base="xs:string">
      <xs:enumeration value="bajo"/>
      <xs:enumeration value="medio"/>
      <xs:enumeration value="alto"/>
    </xs:restriction>
  </xs:simpleType>



  <!-- Restricción de los niveles de los idiomas -->
  <xs:simpleType name="nivel_idioma">
    <xs:restriction base="xs:string">
      <xs:enumeration value="A1"/>
      <xs:enumeration value="A2"/>
      <xs:enumeration value="B1"/>
      <xs:enumeration value="B2"/>
      <xs:enumeration value="C1"/>
      <xs:enumeration value="C2"/>
    </xs:restriction>
  </xs:simpleType>


  <xs:complexType name="T_Experiencia_Laboral">
    <xs:sequence>
      <xs:element name="lugar" type="xs:string" />
      <xs:element name="puesto" type="xs:string" />
      <xs:element name="fecha_inicio" type="xs:date" />
      <xs:element name="fecha_fin" type="xs:date" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="T_competencias">
    <xs:sequence>
      <xs:element name="competencia" type="xs:string" />
      <xs:element name="nivel" type="xs:string" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="T_datos-add">
    <xs:sequence>
      <xs:element name="aficiones" type="xs:string" minOccurs="0" default="Ninguna"/>
      <xs:element name="disponibilidad" type="xs:string" minOccurs="0" />
      <xs:element name="vehiculo_propio" type="xs:string" minOccurs="0" />
      <xs:element name="licencias" type="T_Licencias" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Restricción de los niveles de las licencias de conducir -->
  <xs:simpleType name="T_Licencias">
    <xs:restriction base="xs:string">
      <xs:enumeration value="AM"/>
      <xs:enumeration value="A1"/>
      <xs:enumeration value="A2"/>
      <xs:enumeration value="A"/>
      <xs:enumeration value="B"/>
      <xs:enumeration value="B+E"/>
      <xs:enumeration value="C1"/>
      <xs:enumeration value="C"/>
      <xs:enumeration value="D1"/>
      <xs:enumeration value="D1+E"/>
      <xs:enumeration value="D"/>
      <xs:enumeration value="BTP"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== Mariortega83/LMSGI.1/XML/Curriculum/curriculum.xml
<?xml version="1.0" encoding="UTF-8"?>
<curriculum xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="curriculum.xsd">
    <datos_personales>

        <nombre>Mario</nombre>
        <apellidos>Ortega Pérez</apellidos>
        <fecha_nacimiento>2005-05-04</fecha_nacimiento>
        <lugar_nacimiento>Granada</lugar_nacimiento>
        <nacionalidad>Español</nacionalidad>
        <n_identificacion tipo="nie">93181244H</n_identificacion>
        <archivo_foto></archivo_foto>

    </datos_personales>

    <datos_contacto>

        <tipo_via>Calle</tipo_via>
        <nombre_via>Mirador de Montepinar</nombre_via>
        <numero>1</numero>
        <escalera>Derecha</escalera>
        <piso>2</piso>
        <puerta>B</puerta>
        <codigo_postal>18007</codigo_postal>
        <pais>España</pais>
        <email>mortper0408@ieszaidinvergeles.org</email>
        <telefono_movil>23</telefono_movil>
        <telefono_fijo>0</telefono_fijo>

    </datos_contacto>

    <datos_opcionales>

        <pagina_web>mariortegaperez83.github.io</pagina_web>
        <cuenta_red_social>mario_ortega83</cuenta_red_social>

    </datos_opcionales>


    <formacion_academica>

        <nombre>Titulado en Oxford</nombre>
        <centro>Oxford</centro>
        <fecha_inicio>2023-12-12</fecha_inicio>
        <fecha_fin>2023-12-12</fecha_fin>

    </formacion_academica>
    
    <formacion_academica>

        <nombre>Titulado en Bachillerato Tecnológico</nombre>
        <centro>Centro Salesiano San Juan Bosco</centro>
        <fecha_inicio>2023-12-12</fecha_inicio>
        <fecha_fin>2023-12-12</fecha_fin>

    </formacion_academica>


    <formacion_academica>

        <nombre>Técnico Superior de Desasrrollo de Aplicaciones Web</nombre>
        <centro>IES Zaidin-Vergeles</centro>
        <fecha_inicio>2023-09-15</fecha_inicio>
        <fecha_fin>2025-06-16</fecha_fin>

    </formacion_academica>




    <idiomas>

        <idioma>Ingles</idioma>
        <nivel_comprension_oral>alto</nivel_comprension_oral>
        <nivel_expresion_oral>medio</nivel_expresion_oral>
        <nivel_comprension_escrita>alto</nivel_comprension_escrita>
        <nivel_expresion_escrita>alto</nivel_expresion_escrita>
        <nivel_titulo>A2</nivel_titulo>

    </idiomas>

    <idiomas>

        <idioma>Frances</idioma>
        <nivel_comprension_oral>alto</nivel_comprension_oral>
        <nivel_expresion_oral>medio</nivel_expresion_oral>
        <nivel_comprension_escrita>alto</nivel_comprension_escrita>
        <nivel_expresion_escrita>alto</nivel_expresion_escrita>
        <nivel_titulo>C1</nivel_titulo>

    </idiomas>
    
    <idiomas>

        <idioma>Alemán</idioma>
        <nivel_comprension_oral>alto</nivel_comprension_oral>
        <nivel_expresion_oral>medio</nivel_expresion_oral>
        <nivel_comprension_escrita>alto</nivel_comprension_escrita>
        <nivel_expresion_escrita>alto</nivel_expresion_escrita>
        <nivel_titulo>B2</nivel_titulo>

    </idiomas>


    <experiencia_laboral>

        <lugar></lugar> 
        <puesto></puesto>
        <fecha_inicio>2345-12-12</fecha_inicio>
        <fecha_fin>1232-12-21</fecha_fin>
        
    </experiencia_laboral>


    <competencias_socio-profesionales>

        <competencia></competencia>
        <nivel></nivel>

    </competencias_socio-profesionales>

    <datos_adiccionales>

        <aficiones></aficiones>
        <disponibilidad></disponibilidad>
        <vehiculo_propio></vehiculo_propio>
        <licencias></licencias>

    </datos_adiccionales>

</curriculum>
